CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    email_id VARCHAR(255) NOT NULL,
    type INT NOT NULL DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE plan (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    current_age INT NOT NULL,
    retirement_age INT NOT NULL,
    wist_to_live_till INT NOT NULL,
    current_savings DECIMAL(15,2) NOT NULL,
    inflation_rate DECIMAL(5,2) NOT NULL,
    capital_gains_tax_rate DECIMAL(5,2) NOT NULL,
    income_tax_rate DECIMAL(5,2) NOT NULL,
    salary DECIMAL(15,2) NOT NULL,
    bonus DECIMAL(15,2) NOT NULL,
    investment_income DECIMAL(15,2) NOT NULL,
    rental_income DECIMAL(15,2) NOT NULL,
    other_income DECIMAL(15,2) NOT NULL,
    housing_cost DECIMAL(15,2) NOT NULL,
    transportation_cost DECIMAL(15,2) NOT NULL,
    food_cost DECIMAL(15,2) NOT NULL,
    utilities_cost DECIMAL(15,2) NOT NULL,
    insurance_cost DECIMAL(15,2) NOT NULL,
    entertainment_cost DECIMAL(15,2) NOT NULL,
    healthcare_cost DECIMAL(15,2) NOT NULL,
    debt_payments DECIMAL(15,2) NOT NULL,
    vpf_epf_ppf_amount DECIMAL(15,2) NOT NULL,
    vpf_epf_ppf_irr DECIMAL(5,2) NOT NULL,
    recurring_deposit_amount DECIMAL(15,2) NOT NULL,
    recurring_deposit_irr DECIMAL(5,2) NOT NULL,
    government_bills_amount DECIMAL(15,2) NOT NULL,
    government_bills_irr DECIMAL(5,2) NOT NULL,
    gold_amount DECIMAL(15,2) NOT NULL,
    gold_irr DECIMAL(5,2) NOT NULL,
    corporate_bonds_amount DECIMAL(15,2) NOT NULL,
    corporate_bonds_irr DECIMAL(5,2) NOT NULL,
    largecap_mutual_fund_amount DECIMAL(15,2) NOT NULL,
    largecap_mutual_fund_irr DECIMAL(5,2) NOT NULL,
    direct_stocks_amount DECIMAL(15,2) NOT NULL,
    direct_stocks_irr DECIMAL(5,2) NOT NULL,
    smallcap_mutual_fund_amount DECIMAL(15,2) NOT NULL,
    smallcap_mutual_fund_irr DECIMAL(5,2) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id)
);
